name: e2e-test-elasticache
on:
  # Allow manual trigger of e2e tests
  workflow_dispatch:

jobs:
  test-elasticache-controller:
    name: test elasticache controller
    runs-on: [self-hosted, aws-controllers-k8s]
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: checkout code
        uses: actions/checkout@v2
        with:
          path: community
      - name: Checkout elasticache-controller repo
        uses: actions/checkout@v2
        with:
          repository: aws-controllers-k8s/elasticache-controller
          path: elasticache-controller
      - name: build ack-generate
        run: make build-ack-generate
        working-directory: ./community
      - name: build controller
        run: ./scripts/build-controller.sh $SERVICE
        working-directory: ./community
        env:
          SERVICE: elasticache
      - name: install helm
        run: ./scripts/install-helm.sh
        working-directory: ./community
#      - name: execute e2e tests
#        run: |
#          export AWS_ROLE_ARN=$(aws ssm get-parameter --name ACK_ROLE_ARN | jq -r '.Parameter.Value')
#          export AWS_ROLE_ARN_ALT=$(aws ssm get-parameter --name ACK_ROLE_ARN_ALT | jq -r '.Parameter.Value')
#          ./scripts/kind-build-test.sh $SERVICE
#        working-directory: ./community
#        env:
#          SERVICE: elasticache
